######################################################
# ATTENTION-ATTENTION-ATTENTION-ATTENTION-ATTENTION
# make sure you run this FIRST
# source configure-env-hera-top-node.sh
# ATTENTION-ATTENTION-ATTENTION-ATTENTION-ATTENTION
######################################################

carbonrelay1:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2003:2003"
   - "2004:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay2:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2013:2003"
   - "2014:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay3:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2023:2003"
   - "2024:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay4:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2033:2003"
   - "2034:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay5:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2043:2003"
   - "2044:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay6:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2053:2003"
   - "2054:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay7:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2063:2003"
   - "2064:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay8:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2073:2003"
   - "2074:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon

carbonrelay9:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2083:2003"
   - "2084:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay10:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2093:2003"
   - "2094:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay11:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2103:2003"
   - "2104:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay12:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2113:2003"
   - "2114:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay13:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2123:2003"
   - "2124:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay14:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2133:2003"
   - "2134:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay15:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2143:2003"
   - "2144:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carbonrelay16:
  image: nuancemobility/carbon
  command: relay
  ports:
   - "2153:2003"
   - "2154:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
   
carboncache0:
  image: nuancemobility/carbon
  command: cache
  volumes:
   - ./carbon/cache:/etc/carbon
  volumes_from:
   - ncsmonitoring_whisper_1

graphite1:
  image: nuancemobility/graphite-web
  ports:
   - "80:80"
  environment:
   - HERA_GRAPHITE_WEB_CARBONLINK_HOSTS
   - HERA_GRAPHITE_WEB_CLUSTER_SERVERS
   - HERA_GRAPHITE_WEB_APACHE2_MAX_REQUEST_WORKER
   - HERA_GRAPHITE_WEB_APACHE2_SERVER_LIMIT
   - HERA_GRAPHITE_WEB_APACHE2_THREADS
   - HERA_GRAPHITE_WEB_APACHE2_PROCESSES
   - HERA_GRAPHITE_WEB_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./graphite-web:/etc/graphite
  volumes_from:
   - ncsmonitoring_whisper_1
  links:
   - carboncache0

elasticsearch:
  image: elasticsearch:1.6
  command: -Des.node.name="hera_elasticsearch_001" -Des.bootstrap.mlockall=true
  environment:
   - ES_HEAP_SIZE=1024m
  volumes_from:
   - ncsmonitoring_elasticsearchdata_1

elasticsearchcurator:
  image: nuancemobility/elasticsearch-curator
  links:
   - elasticsearch
  volumes:
   - ./elasticsearch-curator:/config

grafana:
  image: nuancemobility/grafana
  volumes:
   - ./grafana/config.js:/usr/share/grafana/config.js

kibana3:
  image: nuancemobility/kibana
  volumes:
   - ./kibana:/config

kibana4:
  image: kibana:4.1
  links:
   - elasticsearch

logstash:
  image: logstash:1.5
  command: -f /config-dir/
  environment:
   - LS_HEAP_SIZE=2048m
  links:
   - elasticsearch
   - redis
  volumes:
   - ./logstash:/config-dir
   - ./mib:/mib
   - /etc/hera/logstash/ssl:/etc/pki/tls
  ports:
   - "5000:5000/udp"
   - "5001:5001"

redis:
    image: redis:3.0.2
    ports:
        - "6379:6379"

sensu:
  image: nuancemobility/sensu
  links:
   - carbonrelay1
   - rabbitmq
  volumes:
   - ./sensu/config:/etc/sensu/conf.d
   - ./sensu/handlers:/etc/sensu/handlers

uchiwa:
  image: uchiwa/uchiwa
  links:
   - sensu
  volumes:
   - ./uchiwa:/config
  ports:
   - "3000:3000"

sensuclient:
  image: nuancemobility/sensu-client
  volumes:
   - ./sensu-client/config:/etc/sensu/conf.d
   - ./sensu-client/plugins:/etc/sensu/plugins
   - ./mib:/etc/sensu/mib
   - /var/run:/var/run:rw
#   - /sys:/sys:ro
#   - /proc:/proc:ro
  net: "host"
  privileged: true

cadvisor:
  image: google/cadvisor:0.15.1
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
#   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro

monitoringproxy:
  image: nuancemobility/nginx
  links:
   - uchiwa
   - grafana
   - kibana3
   - kibana4
   - elasticsearch
   - cadvisor
   - graphite1
#   - fitnesse
   - configsynchronizer
   - screenshoter
  volumes:
   - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/html:/usr/share/nginx/html
   - /etc/hera/nginx/ssl:/etc/nginx/ssl
   - /etc/hera/nginx/includes:/etc/nginx/includes
  ports:
   - "443:443"
   - "8080:8080"
   - "8888:8888"
   - "4242:4242"

configsynchronizer:
  image: nuancemobility/hera-config-synchronizer
  links:
   - elasticsearch
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200/
   - GIT_REPOSITORY=https://git.labs.nuance.com/ncs-devops/ncs-monitoring-config.git

#fitnesse:
#  image: mtl-mobi-registry:5000/nmt_fitnesse:6.0.100.16.6
#  environment:
#   - CS_GWPORT=8911
#   - CS_APPKEY=525348e77144a9cee9a7471a8b67c50ea85b9e3eb377a3c1a3a23db88f9150eefe76e6a339fdbc62b817595f53d72549d9ebe36438f8c2619846b963e9f43a93
#   - CS_NMAID=SAMPLE_DEBUG_NMAID_TO_BE_REPLACED
#   - CS_GWHOST=mtl-blade19-06.nuance.com

screenshoter:
  image: nuancemobility/web-screenshoter

rabbitmq:
  image: rabbitmq:3.5
  ports:
   - "5672:5672"
