######################################################
# ATTENTION-ATTENTION-ATTENTION-ATTENTION-ATTENTION
# make sure you run this FIRST
# source  configure-env-hera-collector-node.sh
# ATTENTION-ATTENTION-ATTENTION-ATTENTION-ATTENTION
######################################################

carbonrelay1:
  image: nuancemobility/carbon
  command: relay --instance=x
  ports:
   - "2003:2003"
   - "2004:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
  links:
   - carboncache1
   - carboncache2
   - carboncache3
   - carboncache4
   - carboncache5
   - carboncache6
   - carboncache7
   - carboncache8
   - carboncache9
   - carboncache10
   - carboncache11
   - carboncache12
   - carboncache13
   - carboncache14
   - carboncache15
   - carboncache16

carbonrelay2:
  image: nuancemobility/carbon
  command: relay --instance=y
  ports:
   - "2013:2003"
   - "2014:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
  links:
   - carboncache1
   - carboncache2
   - carboncache3
   - carboncache4
   - carboncache5
   - carboncache6
   - carboncache7
   - carboncache8
   - carboncache9
   - carboncache10
   - carboncache11
   - carboncache12
   - carboncache13
   - carboncache14
   - carboncache15
   - carboncache16
   
carboncache1:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper

carboncache2:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache3:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache4:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache5:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache6:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache7:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache8:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache9:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache10:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache11:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache12:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache13:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache14:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache15:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache16:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
graphite1:
  image: nuancemobility/graphite-web
  ports:
   - "80:80"
  environment:
   - HERA_GRAPHITE_WEB_CARBONLINK_HOSTS
   - HERA_GRAPHITE_WEB_CLUSTER_SERVERS
   - HERA_GRAPHITE_WEB_APACHE2_MAX_REQUEST_WORKER
   - HERA_GRAPHITE_WEB_APACHE2_SERVER_LIMIT
   - HERA_GRAPHITE_WEB_APACHE2_THREADS
   - HERA_GRAPHITE_WEB_APACHE2_PROCESSES
   - HERA_GRAPHITE_WEB_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./graphite-web:/etc/graphite
   - /mnt/ramdisk:/var/lib/graphite/whisper
  links:
   - carboncache1
   - carboncache2
   - carboncache3
   - carboncache4
   - carboncache5
   - carboncache6
   - carboncache7
   - carboncache8
   - carboncache9
   - carboncache10
   - carboncache11
   - carboncache12
   - carboncache13
   - carboncache14
   - carboncache15
   - carboncache16
   
graphite2:
  image: nuancemobility/graphite-web
  ports:
   - "81:80"
  environment:
   - HERA_GRAPHITE_WEB_CARBONLINK_HOSTS
   - HERA_GRAPHITE_WEB_CLUSTER_SERVERS
   - HERA_GRAPHITE_WEB_APACHE2_MAX_REQUEST_WORKER
   - HERA_GRAPHITE_WEB_APACHE2_SERVER_LIMIT
   - HERA_GRAPHITE_WEB_APACHE2_THREADS
   - HERA_GRAPHITE_WEB_APACHE2_PROCESSES
   - HERA_GRAPHITE_WEB_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./graphite-web:/etc/graphite
   - /mnt/ramdisk:/var/lib/graphite/whisper
  links:
   - carboncache1
   - carboncache2
   - carboncache3
   - carboncache4
   - carboncache5
   - carboncache6
   - carboncache7
   - carboncache8
   - carboncache9
   - carboncache10
   - carboncache11
   - carboncache12
   - carboncache13
   - carboncache14
   - carboncache15
   - carboncache16

elasticsearch:
  image: elasticsearch:1.6
  command: -Des.node.name="hera_elasticsearch_001" -Des.bootstrap.mlockall=true
  ports:
   - "9200:9200"
   - "9300:9300"
  environment:
   - ES_HEAP_SIZE=1024m
  volumes_from:
   - ncsmonitoring_elasticsearchdata_1

grafana:
  image: nuancemobility/grafana
  ports:
   - "8080:80"
  environment:
   - HERA_GRAFANA_LOCAL_ELASTICSEARCH_URL
   - HERA_GRAFANA_LOCAL_GRAPHITE_URL
   - HERA_GRAFANA_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./grafana/config.js:/usr/share/grafana/config.js
  links:
   - elasticsearch