######################################################
# ATTENTION-ATTENTION-ATTENTION-ATTENTION-ATTENTION
# make sure you run this FIRST
# source  configure-env-hera-collector-node.sh
# ATTENTION-ATTENTION-ATTENTION-ATTENTION-ATTENTION
######################################################

carbonrelay1:
  image: nuancemobility/carbon
  command: relay --instance=x
  ports:
   - "2003:2003"
   - "2004:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
  links:
   - carboncache1
   - carboncache2
   - carboncache3
   - carboncache4
   - carboncache5
   - carboncache6
   - carboncache7
   - carboncache8
   - carboncache9
   - carboncache10
   - carboncache11
   - carboncache12
   - carboncache13
   - carboncache14
   - carboncache15
   - carboncache16

carbonrelay2:
  image: nuancemobility/carbon
  command: relay --instance=y
  ports:
   - "2013:2003"
   - "2014:2004"
  environment:
   - HERA_CARBON_RELAY_DESTINATIONS
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/relay:/etc/carbon
  links:
   - carboncache1
   - carboncache2
   - carboncache3
   - carboncache4
   - carboncache5
   - carboncache6
   - carboncache7
   - carboncache8
   - carboncache9
   - carboncache10
   - carboncache11
   - carboncache12
   - carboncache13
   - carboncache14
   - carboncache15
   - carboncache16
   
carboncache1:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper

carboncache2:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache3:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache4:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache5:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache6:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache7:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache8:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache9:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache10:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache11:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache12:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache13:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache14:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache15:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
carboncache16:
  image: nuancemobility/carbon
  command: cache
  environment:
   - HERA_CARBON_CACHE_RETENTION
   - HERA_CARBON_MAX_CREATES_PER_MINUTE
   - HERA_CARBON_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./carbon/cache:/etc/carbon
   - /mnt/ramdisk:/var/lib/graphite/whisper
   
graphite1:
  image: nuancemobility/graphite-web
  ports:
   - "80:80"
  environment:
   - HERA_GRAPHITE_WEB_CARBONLINK_HOSTS
   - HERA_GRAPHITE_WEB_CLUSTER_SERVERS
   - HERA_GRAPHITE_WEB_APACHE2_MAX_REQUEST_WORKER
   - HERA_GRAPHITE_WEB_APACHE2_SERVER_LIMIT
   - HERA_GRAPHITE_WEB_APACHE2_THREADS
   - HERA_GRAPHITE_WEB_APACHE2_PROCESSES
   - HERA_GRAPHITE_WEB_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./graphite-web:/etc/graphite
   - /mnt/ramdisk:/var/lib/graphite/whisper
  links:
   - carboncache1
   - carboncache2
   - carboncache3
   - carboncache4
   - carboncache5
   - carboncache6
   - carboncache7
   - carboncache8
   - carboncache9
   - carboncache10
   - carboncache11
   - carboncache12
   - carboncache13
   - carboncache14
   - carboncache15
   - carboncache16
   
graphite2:
  image: nuancemobility/graphite-web
  ports:
   - "81:80"
  environment:
   - HERA_GRAPHITE_WEB_CARBONLINK_HOSTS
   - HERA_GRAPHITE_WEB_CLUSTER_SERVERS
   - HERA_GRAPHITE_WEB_APACHE2_MAX_REQUEST_WORKER
   - HERA_GRAPHITE_WEB_APACHE2_SERVER_LIMIT
   - HERA_GRAPHITE_WEB_APACHE2_THREADS
   - HERA_GRAPHITE_WEB_APACHE2_PROCESSES
   - HERA_GRAPHITE_WEB_INIT_SCRIPT_LOG_VERBOSE
  volumes:
   - ./graphite-web:/etc/graphite
   - /mnt/ramdisk:/var/lib/graphite/whisper
  links:
   - carboncache1
   - carboncache2
   - carboncache3
   - carboncache4
   - carboncache5
   - carboncache6
   - carboncache7
   - carboncache8
   - carboncache9
   - carboncache10
   - carboncache11
   - carboncache12
   - carboncache13
   - carboncache14
   - carboncache15
   - carboncache16

elasticsearch:
  image: elasticsearch:1.6
  command: -Des.node.name="hera_elasticsearch_001" -Des.bootstrap.mlockall=true
  environment:
   - ES_HEAP_SIZE=1024m
  volumes_from:
   - ncsmonitoring_elasticsearchdata_1

elasticsearchcurator:
  image: nuancemobility/elasticsearch-curator
  links:
   - elasticsearch
  volumes:
   - ./elasticsearch-curator:/config

grafana:
  image: nuancemobility/grafana
  volumes:
   - ./grafana/config.js:/usr/share/grafana/config.js

kibana3:
  image: nuancemobility/kibana
  volumes:
   - ./kibana:/config

kibana4:
  image: kibana:4.1
  links:
   - elasticsearch

logstash:
  image: logstash:1.5
  command: -f /config-dir/
  environment:
   - LS_HEAP_SIZE=2048m
  links:
   - elasticsearch
   - redis
  volumes:
   - ./logstash:/config-dir
   - ./mib:/mib
   - /etc/hera/logstash/ssl:/etc/pki/tls
  ports:
   - "5000:5000/udp"
   - "5001:5001"

redis:
    image: redis:3.0.2
    ports:
        - "6379:6379"

sensu:
  image: nuancemobility/sensu
  links:
   - carbonrelay1
   - rabbitmq
  volumes:
   - ./sensu/config:/etc/sensu/conf.d
   - ./sensu/handlers:/etc/sensu/handlers

uchiwa:
  image: uchiwa/uchiwa
  links:
   - sensu
  volumes:
   - ./uchiwa:/config
  ports:
   - "3000:3000"

sensuclient:
  image: nuancemobility/sensu-client
  volumes:
   - ./sensu-client/config:/etc/sensu/conf.d
   - ./sensu-client/plugins:/etc/sensu/plugins
   - ./mib:/etc/sensu/mib
   - /var/run:/var/run:rw
#   - /sys:/sys:ro
#   - /proc:/proc:ro
  net: "host"
  privileged: true

cadvisor:
  image: google/cadvisor:0.15.1
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
#   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro

monitoringproxy:
  image: nuancemobility/nginx
  links:
   - uchiwa
   - grafana
   - kibana3
   - kibana4
   - elasticsearch
   - cadvisor
   - graphite1
   - graphite2
#   - fitnesse
   - configsynchronizer
   - screenshoter
  volumes:
   - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/html:/usr/share/nginx/html
   - /etc/hera/nginx/ssl:/etc/nginx/ssl
   - /etc/hera/nginx/includes:/etc/nginx/includes
  ports:
   - "443:443"
   - "8080:8080"
   - "8888:8888"
   - "4242:4242"

configsynchronizer:
  image: nuancemobility/hera-config-synchronizer
  links:
   - elasticsearch
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200/
   - GIT_REPOSITORY=https://git.labs.nuance.com/ncs-devops/ncs-monitoring-config.git

#fitnesse:
#  image: mtl-mobi-registry:5000/nmt_fitnesse:6.0.100.16.6
#  environment:
#   - CS_GWPORT=8911
#   - CS_APPKEY=525348e77144a9cee9a7471a8b67c50ea85b9e3eb377a3c1a3a23db88f9150eefe76e6a339fdbc62b817595f53d72549d9ebe36438f8c2619846b963e9f43a93
#   - CS_NMAID=SAMPLE_DEBUG_NMAID_TO_BE_REPLACED
#   - CS_GWHOST=mtl-blade19-06.nuance.com

screenshoter:
  image: nuancemobility/web-screenshoter

rabbitmq:
  image: rabbitmq:3.5
  ports:
   - "5672:5672"
